### ISSUE TITLE
Error produced if only one available status is found in the data

### ISSUE THREAD

**Issue by nettam** [MSKCC-Epi-Bio/tidycmprsk#103]
For example, the following code:

tidycmprsk::cuminc(Surv(ttdeath, death_cr) ~ trt, trial %>% filter(death_cr == "censor"))

generates the following error:
Error in cmprsk::cuminc(ftime = outcomes[, 1], fstatus = outcomes[, 2],  : 
  NAs in foreign function call (arg 3)

However, note that 
cmprsk::cuminc(ftime=trial$ttdeath[trial$death_cr == "censor"], fstatus=trial$death_cr[trial$death_cr == "censor"], group=trial$trt[trial$death_cr == "censor"])

works just fine...

**Comment by ddsjoberg** [comment]
Dear @nettam , Thank you for the post.

Can you please re-try your code passing a numeric `cmprsk::cuminc(fstatus)`. In the example above, you've passed a factor only keeping the first level, which has a numeric value of `1`. My guess is that `cmprsk::cuminc()` will not work when you pass a vector of zeros (aka all censored).

**Comment by ddsjoberg** [comment]
Dear @nettam , please feel free to reopen this issue when you have the bandwidth to investigate further
