### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Nickrou10** [MSKCC-Epi-Bio/tidycmprsk#104]
Hi, I am attempting to develop a cumulative incidence plot for competing risk analysis, but I am running into the following error: 
**Code**
install.packages("tidycmprsk")
install.packages("dplyr")
install.packages("ggsurvfit")
library(tidycmprsk)
library(dplyr)
library(ggsurvfit)

model_decomp <- tidycmprsk::cuminc(Surv(time, as.factor(status)) ~ bar_treatment, data = test)

*Creating Sample Dataset*
test <- data.frame(
  id = 1:5000,
  bar_treatment = sample(0:1, 5000, replace = TRUE),
  status = sample(0:2, 5000, replace = TRUE),
  time = runif(5000, min = 1, max = 10)
)

**Error:**
! The `.data` argument of `add_column()` must have unique names as of tibble 3.0.0.
ℹ Use `.name_repair = "minimal"`.
Run `rlang::last_trace()` to see where the error occurred.

I am not sure if this is an issue with the "as.factor(status)", but I otherwise receive an error for invalid status value if I pass as a numeric value. 

Do you know how to resolve this issue? Is there an issue with how i have built my dataset? 

Thank you!

**Comment by ddsjoberg** [comment]
Dear @Nickrou10 ,

Can you please update your post with a minimal reproducible example, aka a reprex. This is the minimum amount of code to illustrate your issue as well as example data we can use to run locally.

**Comment by Nickrou10** [comment]
I have updated with a sample! Interestingly, when I run the code on the sample it does not show the error. I cannot provide access to the actual data, but are you aware of any issues that might cause the error? 
I tested the function on a few different subsets, and only have the issue when I include the first ~5000 observations. I realize you may not be able to help with this issue, but I figured I'd ask in case. Thanks again!

**Comment by ddsjoberg** [comment]
Hi @Nickrou10 ,

Thanks for updating. If you delve further into your data, find the row(s) that cause the error, and update the example, we'll be happy to investigate.

**Comment by Nickrou10** [comment]
I identified the rows, and there is nothing unique to them. Is there anything else that I can do? Thanks

**Comment by ddsjoberg** [comment]
Hmmm without an example I can run, I'm not sure what the next steps would be. Sorry!

**Comment by Nickrou10** [comment]
Hi! I think I resolved the issue!! My original dataframe had several decimal points (0.010000000) for the time variable. I rounded it to three and am no longer having the issue. Just thought I would let you know in case a similar issue arises another time. I appreciate the support, take care!

**Comment by ddsjoberg** [comment]
Thanks for reporting back! That is very strange.

It would still be helpful to post an example here, and we can look into the details. Certainly very small numbers shouldn't be an issue.

Another thing to check is if you can replicate the error directly in cmprsk package

**Comment by mattsecrest** [comment]
I encountered the same error. The problem is when you have two doubles which get rounded to the same number when `cmprsk::timepoints()` is called, eg here: https://github.com/MSKCC-Epi-Bio/tidycmprsk/blob/d9acd3084a44266f7462197dae1093c6bf5fc039/R/broom_methods.R#L209
```
library(tibble)
options(digits = 22)
df <- tibble(
   months = c(2.102669404517449880387, 2.102669404517453877190, 2.102669404517449880387, 2.102669404517453877190, 2.102669404517449880387, 2.102669404517453877190),
   event = factor(c(1,2,3,1,2,3), levels = c(1,2,3), labels = c("A", "B", "C"))
)
unique(df$months)

cuminc(Surv(months, event) ~ 1, data = df)

Error:
! The `.data` argument of `add_column()` must have unique names as of tibble 3.0.0.
ℹ Use `.name_repair = "minimal"`.
Run `rlang::last_trace()` to see where the error occurred.
```

Seems like an issue with `cmprsk`
