### ISSUE TITLE
adding weights in crr function

### ISSUE THREAD

**Issue by abduazizR** [MSKCC-Epi-Bio/tidycmprsk#105]
First of all, many thanks for the great package.

I am wondering if it's possible to incorporate weights into crr. Unlike conventional regression functions where usually there is an argument for `weights`, this does not seem to be the case with crr(). Hopefully, there is a way to incorporate weights into crr.

**Comment by ddsjoberg** [comment]
Thanks for the post @abduazizR !

`tidycmprk:crr()` is a wrapper for `cmprsk::crr()`, so we are unable to add additional statistical options when they are not present in {cmprsk}, unfortunately.
