### ISSUE TITLE
The computational analysis of the crr model is time-consuming

### ISSUE THREAD

**Issue by gustavomodelli** [MSKCC-Epi-Bio/tidycmprsk#106]
I am currently engaged in a regression analysis aimed at predicting the likelihood of kidney transplantation within Brazil's national transplant system. The most effective model identified thus far is a Competing Risks model, which accounts for death as a concurrent event and transplant as the primary outcome. However, I'm encountering challenges with the computational aspect due to the sizable database, which comprises 124,348 cases. Executing the computations using the 'crr' function from the 'tidycmprsk' package is proving to be time-consuming, taking several hours to complete, and I am unable to finalize the analysis on my notebook. Do you have any suggestions on how to expedite these computations? Perhaps through the implementation of a parallel processing approach?

**Comment by ddsjoberg** [comment]
The tidycmprsk package simply wraps the cmprsk package and gives it a modern interface. You will save some computation time by using `cmprsk::crr()` directly.

Good luck
