### ISSUE TITLE
`crr()` function does not work using the `with()` function

### ISSUE THREAD

**Issue by ABohynDOE** [MSKCC-Epi-Bio/tidycmprsk#107]
To fit a competing risk model with the `tidycmprsk` package I can use the following syntax

``` r
library(tidycmprsk)
#> Warning: package 'tidycmprsk' was built under R version 4.3.2

crr_mod <- crr(Surv(ttdeath, death_cr) ~ age + trt, trial)
#> 11 cases omitted due to missing values
```

However, if I want to run the model using the `with` syntax, it does not work

``` r
library(tidycmprsk)
#> Warning: package 'tidycmprsk' was built under R version 4.3.2

crr_mod <- with(trial, crr(Surv(ttdeath, death_cr) ~ age))
#> ✖ There was an error evaluating the LHS of the formula.
#> Error: Error in crr.formula(Surv(ttdeath, death_cr) ~ age): argument "data" is missing, with no default
```

Is this on a normal behavior or is this a bug ? 

## Context

The reason I might want to use this syntax is if I want to pool estimates from several competing risk models when using multiple imputation.
For example, if I impute the 11 missing values in the `age` column, I can then fit a model for each imputation and combine the results.
However, to combine the estimates I need to fit the model using the `with` syntax.

``` r
library(tidycmprsk)
#> Warning: package 'tidycmprsk' was built under R version 4.3.2

imp <- mice::mice(trial)

pooled_crr_mod <- with(trial, crr(Surv(ttdeath, death_cr) ~ age))
#> ✖ There was an error evaluating the LHS of the formula.
#> Error: Error in crr.formula(Surv(ttdeath, death_cr) ~ age): argument "data" is missing, with no default

mice::pool(pooled_crr_mod)
#> Error in eval(expr, envir, enclos): object 'pooled_crr_mod' not found
```

<sup>Created on 2024-05-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

If the current behavior of `crr()` is normal, is there a workaround to use for this context ?

**Comment by ddsjoberg** [comment]
Dear @ABohynDOE , thanks for the post. Both the `crr(formula, data)` are expected to be passed to the function. That's correct, right @tengfei-emory ?

We can, however, make the error message more clear in this case.

**Comment by ABohynDOE** [comment]
Thanks for the answer @ddsjoberg ! I think that the message is already clear enough, I was simply wondering if this was normal behavior or not
