### ISSUE TITLE
Add recipes methods for `crr()` and `cuminc()`

### ISSUE THREAD

**Issue by ddsjoberg** [MSKCC-Epi-Bio/tidycmprsk#11]

**Comment by tengfei-emory** [comment]
Looks like `recipe` does not take `Surv` object. Unlike `mold` which we found a way to get around, `recipe` will give error message at the first place if LHS of the formula is a `Surv` object:

`recipe(Surv(ttdeath, death_cr) ~ age + stage, trial, failcode = 1) %>% step_dummy(stage)`

> Error: No in-line functions should be used here; use steps to define baking actions.
> Run `rlang::last_error()` to see where the error occurred.

> <error/rlang_error>
> No in-line functions should be used here; use steps to define baking actions.
> Backtrace:
> 1. +-recipes::recipe(...)
> 2. \-recipes:::recipe.formula(...)
> 3.   \-recipes:::form2args(formula, data, ...)
> 4.     \-recipes:::inline_check(formula)

**Comment by ddsjoberg** [comment]
Hmmm, there is so much I need to learn about tidymodels....maybe recipes isn't the way we're meant to do it?

Perhaps, we should use something like `survival_reg()` and create a tidycmprsk engine?
https://parsnip.tidymodels.org/reference/survival_reg.html

Whatever we decide on, we can make this our last priority.

**Comment by tengfei-emory** [comment]
Actually `recipe` can be directly transformed as `formula`. I just add one extra line to incorporate `recipe` into `crr`. Please check the new branch I created. What do you think?

An example of working with recipe is following:

```
trial$survobj <- Surv(trial$ttdeath, trial$death_cr)
rec <- recipe(survobj ~ age + grade, trial) %>% prep()
crr(rec, trial)
```
Annoyingly, `recipe` only accepts `Surv` objects which are already created in a dataset. It will show error if the `Surv` object is directly put in the formula.

**Comment by tengfei-emory** [comment]
I think there are some compatibility issues for the `formula` translated from a `recipe` object. For example, I can create the following `recipe` object by specifying dummy variables for a categorical variable:

```
trial$survobj <- Surv(trial$ttdeath, trial$death_cr)
rec <- recipe(survobj ~ age + grade, trial) 
                         %>% step_dummy(grade) 
                         %>% prep()
```

Then the corresponding formula would be `formula(rec)`, which is `survobj ~ age + grade_II + grade_III`. This formula contains dummy variables which is not actually created for the original data, which means it's not straightforward to directly apply `model.frame` by this `formula` and `data`. This is not compatible with our current output object `new_crr` which utilize `model.frame` for `formula` and `data` used by `hardhat` methods. 

Therefore, I think some compatibility efforts should be made to fully facilitate `recipe` for this package...

**Comment by tengfei-emory** [comment]
After experiencing some awkward compatibility issues we decided to put `recipe` aside till there are some better solutions. It is not practical to ask users to create a `Surv` object under the original data matrix before creating a recipe...
