### ISSUE TITLE
Investigate how various contrasts may affect the results of `crr()`

### ISSUE THREAD

**Issue by ddsjoberg** [MSKCC-Epi-Bio/tidycmprsk#18]

**Comment by tengfei-emory** [comment]
It turns out that the ordered factors serve for the purpose of trend test.

For example, `model.matrix(Surv(ttdeath, death_cr) ~ age + grade, trial)` creates a design matrix with **dummy variables** for `grade`, such that the regression model for this design matrix will also explain the differences between different levels of `grade` and the reference level of `grade`.

However, `model.matrix(Surv(ttdeath, death_cr) ~ age + ordered(grade), trial)` creates a design matrix with **[polynomial contrast](https://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/#:~:text=4-,Orthogonal%20Polynomial%20Coding,-Orthogonal%20polynomial%20coding)**, which is used for [trend test](https://en.wikipedia.org/wiki/Linear_trend_estimation). Correspondingly, the `mold` function will take those created contrast structure into its resulting `predictors`.

I think the safest choice is to prohibit the use of `ordered` factors in `crr()` because (1) it is hard to interpret those trend estimates for the Fine and Gray's model, and (2) I cannot find the use of polynomial contrast for Fine and Gray's model at least from Google. 

In terms of `cuminc()`, `ordered` contrasts are not even integers, which cannot be transformed as `groups`. Therefore, we should also disallow `ordered()` in `cuminc()`. What do you think?

**Comment by tengfei-emory** [comment]
This article also discusses the polynomial contrast: https://data.library.virginia.edu/understanding-ordered-factors-in-a-linear-model/.

**Comment by ddsjoberg** [comment]
hey @tengfei-emory ,

I will need to read more before I can say whether or not the contrasts should forbidden in `crr()`. My initial impression is that if `mold()` prepares the dummy data matrix appropriately regardless of any contrasts used, then perhaps they are ok to accept.

I compared our results to those in the survival package, and the results are the same (or close enough given the different underlying implementations).

``` r
library(tidycmprsk)

trial %>%
  dplyr::mutate(grade = ordered(grade)) %>%
  {crr(Surv(ttdeath, death_cr) ~ grade, data = .)}
#> 
#> -- crr() -----------------------------------------------------------------------
#> * Call Surv(ttdeath, death_cr) ~ grade
#> * Failure type of interest "death from cancer"
#> 
#> Variable   HR     SE      95% CI       p-value    
#> grade.L    1.25   0.219   0.81, 1.92   0.31       
#> grade.Q    1.14   0.242   0.71, 1.83   0.59

trial %>%
  dplyr::mutate(grade = ordered(grade)) %>%
  {survival::finegray(Surv(ttdeath, death_cr) ~ grade, data = .)} %>%
  {survival::coxph(Surv(fgstart, fgstop, fgstatus) ~ grade, data = .)}
#> Call:
#> survival::coxph(formula = Surv(fgstart, fgstop, fgstatus) ~ grade, 
#>     data = .)
#> 
#>           coef exp(coef) se(coef)     z     p
#> grade.L 0.2215    1.2480   0.2248 0.986 0.324
#> grade.Q 0.1293    1.1381   0.2368 0.546 0.585
#> 
#> Likelihood ratio test=1.3  on 2 df, p=0.523
#> n= 200, number of events= 57
```

<sup>Created on 2021-10-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I do agree contrasts should not be allowed in `cuminc()` because  that function is only stratifying and the contrasts will have no effect there. Not sure how to check for them though! Maybe there is no need to check, because regardless of the contrast used, `cuminc()` will treat every unique level as a group.....

**Comment by ddsjoberg** [comment]
Looks like the poly contrast doesn't cause any issues in `cuminc()`...it just treats each level uniquely.

``` r
library(tidycmprsk)

trial %>%
  dplyr::mutate(grade = ordered(grade)) %>%
  {cuminc(Surv(ttdeath, death_cr) ~ grade, data = .)}
#> 
#> -- cuminc() --------------------------------------------------------------------
#> * Failure type "death from cancer"
#> strata   time   estimate   std.error    
#> I        5.00   0.000      0.000        
#> I        10.0   0.000      0.000        
#> I        15.0   0.103      0.037        
#> I        20.0   0.176      0.047        
#> II       5.00   0.000      0.000        
#> II       10.0   0.044      0.025        
#> II       15.0   0.147      0.043        
#> II       20.0   0.221      0.051        
#> III      5.00   0.000      0.000        
#> III      10.0   0.047      0.027        
#> III      15.0   0.109      0.039        
#> III      20.0   0.250      0.055
#> * Failure type "death other causes"
#> strata   time   estimate   std.error    
#> I        5.00   0.000      0.000        
#> I        10.0   0.000      0.000        
#> I        15.0   0.044      0.025        
#> I        20.0   0.162      0.045        
#> II       5.00   0.000      0.000        
#> II       10.0   0.044      0.025        
#> II       15.0   0.118      0.039        
#> II       20.0   0.191      0.048        
#> III      5.00   0.016      0.016        
#> III      10.0   0.031      0.022        
#> III      15.0   0.109      0.039        
#> III      20.0   0.266      0.056
#> * Tests
#> outcome              statistic   df     p.value    
#> death from cancer    1.33        2.00   0.51       
#> death other causes   2.21        2.00   0.33

trial %>%
  {cuminc(Surv(ttdeath, death_cr) ~ grade, data = .)}
#> 
#> -- cuminc() --------------------------------------------------------------------
#> * Failure type "death from cancer"
#> strata   time   estimate   std.error    
#> I        5.00   0.000      0.000        
#> I        10.0   0.000      0.000        
#> I        15.0   0.103      0.037        
#> I        20.0   0.176      0.047        
#> II       5.00   0.000      0.000        
#> II       10.0   0.044      0.025        
#> II       15.0   0.147      0.043        
#> II       20.0   0.221      0.051        
#> III      5.00   0.000      0.000        
#> III      10.0   0.047      0.027        
#> III      15.0   0.109      0.039        
#> III      20.0   0.250      0.055
#> * Failure type "death other causes"
#> strata   time   estimate   std.error    
#> I        5.00   0.000      0.000        
#> I        10.0   0.000      0.000        
#> I        15.0   0.044      0.025        
#> I        20.0   0.162      0.045        
#> II       5.00   0.000      0.000        
#> II       10.0   0.044      0.025        
#> II       15.0   0.118      0.039        
#> II       20.0   0.191      0.048        
#> III      5.00   0.016      0.016        
#> III      10.0   0.031      0.022        
#> III      15.0   0.109      0.039        
#> III      20.0   0.266      0.056
#> * Tests
#> outcome              statistic   df     p.value    
#> death from cancer    1.33        2.00   0.51       
#> death other causes   2.21        2.00   0.33
```

<sup>Created on 2021-10-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by tengfei-emory** [comment]
After our investigation, different choices of contrasts do not affect the model fitting, although they do have large impacts on interpretations.
