### ISSUE TITLE
Error with categorical univariate crr() and gtsummary::tbl_regression()

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/tidycmprsk#24]
Thank you for this great package!

When I try to run a univariate categorical `crr()` through `tbl_regression()` I get the following error:

```r
crr(Surv(ttdeath, death_cr) ~ trt, trial) %>%
  gtsummary::tbl_regression()
```

`Error: Join columns must be present in data.
x Problem with  variable.`

This is no longer an issue when I add in another categorical or continuous covariate:

```r
crr(Surv(ttdeath, death_cr) ~ trt + age, trial) %>%
  gtsummary::tbl_regression()
```

Is this an issue with `xlevels` in the `new_crr()` function? When I add `drop= FALSE` to `xlevels = `

```r
  hardhat::new_model(
    coefs = coefs %>% stats::setNames(coef_names),
    formula = formula,
    data = data,
    failcode = failcode,
    xlevels =
      stats::model.frame(formula, data = data)[, -1, drop = FALSE] %>%
      purrr::map(
        function(.x) {
          if (inherits(.x, "factor")) return(levels(.x))
          if (inherits(.x, "character")) return(unique(.x) %>% sort())
          return(NULL)
        }
      ) %>%
      purrr::compact(),
    tidy = tidy,
    cmprsk = cmprsk,
    model = data,
    blueprint = blueprint,
    class = "tidycrr"
  )
}
```

it seems to work!

**Comment by ddsjoberg** [comment]
Thank you for reporting AND hunting down the issue!

``` r
library(tidycmprsk)

tbl <-
  crr(Surv(ttdeath, death_cr) ~ trt, trial) %>%
  gtsummary::tbl_regression()
```
![image](https://user-images.githubusercontent.com/26774684/140313385-9e5e3328-3de1-4f95-b6ae-9f465bdc8ae5.png)

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
