### ISSUE TITLE
More customization to aes_args in autoplot()

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/tidycmprsk#25]
I would like to color the lines of my `autoplot()` by outcome type. For example:

```r
object <- cuminc(Surv(ttdeath, death_cr) ~ 1, trial)

df_tidy <-
  tidy(object) %>%
  dplyr::bind_rows(
    dplyr::select(., dplyr::any_of(c("outcome", "strata", "time", "estimate"))) %>%
        dplyr::mutate(dplyr::across(c(.data$time, .data$estimate), ~0)) %>%
        dplyr::distinct())
  
ggplot(data = df_tidy,
         aes(x = time, y = estimate,
             linetype = outcome, color = outcome)) +
    geom_step()
``` 

Would it be possible to pass additional custom `aes_args` to the function that would add on/override the defaults, or is this outside the scope of the function?

Thanks again for your work on this package!

**Comment by ddsjoberg** [comment]
Thank you for the reports!!

What kind of API would you like to see to add this functionality? At the moment, stratified groups are shown with different colors, and different outcome types use the linetype arg.

Do you prefer something like `autoplot(x, ...)` where everything in the dots goes to `aes()`, or something like `autoplot(x, aes_args, ...)`

**Comment by ddsjoberg** [comment]
hey hey @karissawhiting !

I made two updates
1. I updated the `tidy()` function to include the estimate at time = 0. This makes is very simple to obtain the data needed to create the figure in `autoplot()`.
2. I added an `autoplot(aes=)` argument that allows you to have more control over the output plot. BUT, now that the `tidy()` function returns time 0 by default, I think it's easier to create the plot from scratch rather than learn the `aes=` argument.

Can you take a look? Do you think it's worth keeping the `aes=` argument at all?

**Comment by karissawhiting** [comment]
Hi Dan. This sounds great, I will take a look. It sounds like making a customized plot from scratch is pretty easy now, but I wonder if it would still be helpful to have a light wrapper that does it for you with some customization capabilities and also maybe includes  `bstfun::add_cuminc_risktable()` capabilities? Like our own `ggsurvplot()/ggcompetingrisks()`. 

On a related note, does `bstfun::add_cuminc_risktable()` work with {tidycmprsk} `cuminc` objects? I couldn't get it to work, but may be specificying it wrong. If not, I can add an issue to bstfun. 

Thanks again for making our competing risks life easier!

**Comment by ddsjoberg** [comment]
1. I"ll keep the `aes=` argument for now, Hopefullly, in the future we can make the autoplot function even better with risk tables or something.
2. In the `cuminc()` object, extract the original fit with call `"cmprsk"` and then pass that object to the plot method.

**Comment by ddsjoberg** [comment]
@karissawhiting i think this is ready to be closed?

please re-open if needed
