### ISSUE TITLE
Definition of `n.event` and `n.censor` ?

### ISSUE THREAD

**Issue by ddsjoberg** [MSKCC-Epi-Bio/tidycmprsk#49]
In the figure below (from visR), the `n.event` and `n.censor` are reported below the figure. I am not 100% certain what the definition is, however. My guess is that it's the number of events that occurred in the interval. For example, were there 4 events in the interval (0, 20] and 2 events in the interval (20, 40] in the placebo group? If that is correct, should we update our `n.event` and `n.censor` definitions when `tidy.ticycuminc(x, times = time_vec)` is called with a non-NULL time argument?

![image](https://user-images.githubusercontent.com/26774684/147881016-0bf4f364-f213-4fb2-95f7-23bd54cb44c2.png)

**Comment by tengfei-emory** [comment]
Will investigate this later. I think there should be some quick modifications to get the above numbers.

**Comment by tengfei-emory** [comment]
Just created a new branch named "interval.event". The `tidycuminc` function in that branch will return the number of events and censored observations in customized time intervals given by `times`. In output the two quantities are named `interval.event` and `interval.censor` but we can rename them, or replace `n.event` and `n.censor` with them.
