### ISSUE TITLE
Add check that `Surv(time2=)` is not passed by users

### ISSUE THREAD

**Issue by ddsjoberg** [MSKCC-Epi-Bio/tidycmprsk#55]
cmprsk needs the origin to time = 0, and we're currently not checking for this.
1. We can let users specify `Surv(time, time2)` but then we'll need to correct the times ourselves
2. Or we can add a check that they did not pass `time2=`

We should add this before the release.

``` r
tidycmprsk::trial |>
  dplyr::mutate(
    ttdeath2 = ttdeath + abs(rnorm(n = dplyr::n()))
  ) |>
  with(survival::Surv(ttdeath, ttdeath2, death_cr)) |>
  unclass() |>
  head()
#>      start     stop status
#> [1,] 24.00 24.72068      0
#> [2,] 24.00 24.83255      0
#> [3,] 24.00 25.15459      0
#> [4,] 17.64 18.25819      2
#> [5,] 16.43 17.67317      2
#> [6,] 15.64 16.56499      1
```

<sup>Created on 2022-01-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
The check was already there! If users pass something in `time2` it change the `type` and we already have a type argument. I updated the documentation to indicate that the `time2=` arg cannot be used.

**Comment by tengfei-emory** [comment]
I will check it out later today!

**Comment by tengfei-emory** [comment]
I just checked the PR. Looks like only `crr` function was modified. Do we need the same error message for `cuminc`?

**Comment by ddsjoberg** [comment]
> I just checked the PR. Looks like only `crr` function was modified. Do we need the same error message for `cuminc`?

It was an update in `as_numeric_failcode()` which is used by both `crr()` and `cuminc()`
