### ISSUE TITLE
Different label headers in tbl_cuminc

### ISSUE THREAD

**Issue by ramashka328** [MSKCC-Epi-Bio/tidycmprsk#88]
Hello, 

I wanted to know, how could I set different labels for columns in tbl_cuminc. My desired output should have column names as 100 day TRM and 5 year TRM.

![image](https://user-images.githubusercontent.com/62358970/198821285-bbadebc2-80a8-4984-8638-f5230eddbc1e.png)

The code:
tidycmprsk::cuminc(Surv(years_new, as.factor(trm))~period, data=donor_MUD) %>% 
  tbl_cuminc(
    times = c(0.27, 5), 
    label_header = "**{time} year TRM**",
    estimate_fun = ~gtsummary::style_sigfig(.x, scale = 100, digits=3)) %>% 
  add_p() %>% add_nevent(location = c("label", "level")) %>%
  add_n(location = c("label", "level"))

**Comment by ddsjoberg** [comment]
These tables are {gtsummary} tables and you can use any of those functions to change the header. Use the `modify_header()` function to change the headers.
https://www.danieldsjoberg.com/gtsummary/reference/modify.html
