### ISSUE TITLE
Using restricted cubic splines and natural splines with tidycmprsk

### ISSUE THREAD

**Issue by SoumyaRo** [MSKCC-Epi-Bio/tidycmprsk#94]
Is there a way that we use a restricted cubic spline or a natural spline with crr (multivariable) in tidycmprsk?
Thanks in advance.

**Comment by ddsjoberg** [comment]
Dear @SoumyaRo , using splines in this package should work just like any other modeling package. If you experience a bug, please file an issue with a minimal reproducible example (aka a reprex).

Thank you for the post!
