### ISSUE TITLE
'Note' on 'sqrt' and 'seq_len' issued during install

### ISSUE THREAD

**Issue by mjtjmjtj** [MSKCC-Epi-Bio/tidycmprsk#97]
Below find installation messages and sessionInfo. Its is the
  Note: wrong number of arguments to 'sqrt' 
  Note: wrong number of arguments to 'seq_len' 
that are of concern. Manual check shows that mentioned functions are part of base. In mode detail
  ?sqrt  ->  MathFun {base}
  ?seq_len  ->  seq {base}

> install.packages("tidycmprsk", repo = "https://cran.rstudio.com/")
Installing package into ‘/scer/homedirs/mjtj/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/tidycmprsk_0.2.0.tar.gz'
Content type 'application/x-gzip' length 291024 bytes (284 KB)
==================================================
downloaded 284 KB

* installing *source* package ‘tidycmprsk’ ...
** package ‘tidycmprsk’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Note: wrong number of arguments to 'sqrt' 
Note: wrong number of arguments to 'seq_len' 
** help
*** installing help indices
  converting help for package ‘tidycmprsk’
    finding HTML links ... done
    add_cuminc                              html  
    autoplot.tidycuminc                     html  
    base_methods_crr                        html  
    base_methods_cuminc                     html  
    broom_methods_crr                       html  
    broom_methods_cuminc                    html  
    crr                                     html  
    cuminc                                  html  
    predict.tidycrr                         html  
    print                                   html  
    reexports                               html  
    tbl_cuminc                              html  
    tidycmprsk-package                      html  
    trial                                   html  
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (tidycmprsk)

The downloaded source packages are in
	‘/tmp/RtmpnCp8DH/downloaded_packages’
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux 8.8 (Ootpa)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.15.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] fansi_1.0.3      assertthat_0.2.1 dplyr_1.0.9      utf8_1.2.2       crayon_1.5.1     grid_4.2.0       R6_2.5.1         DBI_1.1.2       
 [9] lifecycle_1.0.3  gtable_0.3.0     magrittr_2.0.3   scales_1.2.0     pillar_1.7.0     ggplot2_3.4.0    rlang_1.0.6      cli_3.6.0       
[17] rstudioapi_0.13  generics_0.1.2   vctrs_0.5.2      ellipsis_0.3.2   tools_4.2.0      glue_1.6.2       purrr_0.3.4      munsell_0.5.0   
[25] compiler_4.2.0   pkgconfig_2.0.3  colorspace_2.0-3 tidyselect_1.1.2 tibble_3.1.7    
>

**Comment by ddsjoberg** [comment]
Thank you for the post @mjtjmjtj !

**Comment by ddsjoberg** [comment]
The note has been updated with more information. I am still not sure what is going on!?

```
Note: wrong number of arguments to 'sqrt' at broom_methods.R:214 
Note: wrong number of arguments to 'seq_len' at print.R:167 
```

**Comment by elgabbas** [comment]
I am receiving the same note message in my personal R package. The problem is because of using the pipe operator `%>%`

You need to replace, e.g.
```
1:10 %>% sqrt()
10 %>% seq_len()
```
with 
```
1:10 %>% sqrt(x = .)
10 %>% seq_len(length.out = .)
```

Cheers
