### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by dublinQAQ** [MSKCC-Epi-Bio/tidycmprsk#98]
`rt1=rt[,c('futime','fustat','cri')]
rt1$fustat=factor(rt1$fustat)
rt1=as_tibble(rt1)
tidycmprsk::cuminc(Surv(futime,fustat)~cri,data=rt1)`
Errror: ! The .data argument of add_column() must have unique names as of tibble 3.0.0. ℹ Use .name_repair = "minimal".
How to fix this error?

**Comment by ddsjoberg** [comment]
Please update your post with a minimal reproducible example we can run on our machines, and only then can we investigate. Please re-open this issue after you have updated the post. thank you
